<?php
namespace app\admin\controller;

use think\Controller;


/**
 * Created by PhpStorm.
 * User: allen
 * Date: 4/18/2017
 * Time: 11:55 AM
 */
class Admin extends Controller
{
        public function _initialize()
        {
            parent::_initialize(); // TODO: Change the autogenerated stub
            $userInfo=session('user');
            if(empty($userInfo)){
                $this->error('请您登录',url("admin/entry/login"));
            }else{
                $this->assign('loginuser',$userInfo);
            }
        }
}