<?php
/**
 * Created by PhpStorm.
 * User: allen
 * Date: 4/18/2017
 * Time: 11:57 AM
 */

namespace app\common\controller;


use think\Controller;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $langCode=get_l();
        $menu_cate=db('product_category')->where(["status"=>1])->order('sort')->select();
        foreach($menu_cate as $k => $v){
            $menu_cate[$k]["products"]=db("product")->where(["cid"=>$v["id"],'status'=>1])->order('istop desc,top_sort asc')->select();
        }

        $contacts=db('contact')->find();
        $this->assign('contacts',$contacts);

        $this->assign('menu',$menu_cate);
        $this->assign('lang_code',$langCode);
    }
}